export const relayUrls: Relays = [
	{ id: '4D3BAE98-0FAD-4659-A4FF-EFD8B75DC559', address: 'wss://nostr-pub.wellorder.net' },
	{ id: 'FAE831DC-64CE-4D83-8576-B0495BF0D1EB', address: 'wss://relay.nostr.ch' },
	{ id: '90CDD2D2-1000-4C85-AC25-10EAE70F30B4', address: 'wss://relay.damus.io' },
	{ id: '709D8449-4094-46F7-87DF-3A0A0F782E26', address: 'wss://nostr.openchain.fr' },
	// 'wss://relay.nostr.ch',
	// 'wss://nostr-relay.alekberg.net',
	// 'wss://nostr.bitcoiner.social',
	// 'wss://nostr.openchain.fr',
	// 'wss://nostr.zebedee.cloud',
	// 'wss://nostr.chaker.net',
	// 'wss://relay.cryptocculture.com',
	// 'wss://nostr.coollamer.com',
	// 'wss://relay.nostrich.de',
	// 'wss://no-str.org',
	// 'wss://relay.nostr.scot',
	// 'wss://jiggytom.ddns.net',
	// '/wss://nostr.nodeofsven.com',
	// 'wss://nostr.drss.io',
	// 'wss://relay.damus.io',
	// 'wss://nostr.p2sh.co',
	// 'wss://nostr.yael.at',
	// 'wss://relay.taxi',
]
